In [1]:
import numpy as np
from data_generator.batch_generator import BatchGenerator
import data_generator.batch_generator_functions as bgf
from utils.util_functions import convert_float_to_binary_mask
from utils.util_functions import convert_mask_to_cup_format
from model.metric_functions.cup_f1_score import cup_f1_score



In [2]:
BATCH_SIZE = 2
LENGTH = 8
SAMPLE_OFFSET = 0
SAMPLE_FREQ = 4
CENTER = 4
CENTER_OFFSET = 2
IGNORE = ['zeros_ts']

In [3]:
# sample_ts_1
sample_ts_1 = np.array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1])
# leads to 3 samples
y_1 = [[0, 0, 0, 1, 1, 1, 0, 0], [1, 1, 0, 0, 1, 1, 0, 0], [1, 1, 0, 0, 1, 1, 0, 0]]

# sample_ts_2
sample_ts_2 = np.array([0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0])
# leads to 2 samples
y_2 = [[0, 1, 1, 0, 1, 1, 0, 1], [1, 1, 0, 1, 1, 0, 0, 0]]

In [4]:
# batches
batches_true = np.array([
    [[0, 0, 0, 1, 1, 1, 0, 0], [1, 1, 0, 0, 1, 1, 0, 0]],
    [[1, 1, 0, 0, 1, 1, 0, 0], [0, 1, 1, 0, 1, 1, 0, 1]],
    [[1, 1, 0, 1, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]
])

batches_pred = np.array([
    [[0.2, 0.3, 0.4, 0.7, 0.3, 0.3, 0.2, 0.3], [0.6, 0.8, 0.2, 0.2, 0.8, 0.5, 0.2, 0.1]],
    [[0.4, 0.8, 0.4, 0.2, 0.5, 0.7, 0.3, 0.2], [0.1, 0.9, 0.7, 0.2, 0.8, 0.8, 0.2, 0.1]],
    [[0.8, 0.9, 0.1, 0.8, 0.9, 0.2, 0.1, 0.1], [0.0, 0.1, 0.1, 0.0, 0.1, 0.3, 0.1, 0.0]]
])
batches_pred.shape

(3, 2, 8)

In [5]:
table = [
    [('sample_ts_1', 2, [0, 4])],
    [
        ('sample_ts_1', 1, [8]),
        ('sample_ts_2', 1, [0])
    ],
    [
        ('sample_ts_2', 1, [4]),
        ('zeros_ts', 1, [0])
    ]
]

In [37]:
"""
batches_true = np.array([
    [[0, 0, 0, 1, 1, 1, 0, 0], [1, 1, 0, 0, 1, 1, 0, 0]],
    [[1, 1, 0, 0, 1, 1, 0, 0], [0, 1, 1, 0, 1, 1, 0, 1]],
    [[1, 1, 0, 1, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]
])
"""
ts_true = bgf.convert_batches_to_ts(data=batches_true, batch_table=table, center=CENTER, center_offset=CENTER_OFFSET)
ts_true

[array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0])]

In [7]:
ts_true = bgf.convert_batches_to_ts(data=batches_true, batch_table=table, center=CENTER, center_offset=CENTER_OFFSET, ignore=IGNORE)
ts_true

[array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0])]

In [9]:
ts_pred = bgf.convert_batches_to_ts(data=batches_pred, batch_table=table, center=CENTER, center_offset=CENTER_OFFSET, ignore=IGNORE)
ts_pred

[array([0.2, 0.3, 0.4, 0.7, 0.3, 0.3, 0.2, 0.2, 0.8, 0.5, 0.4, 0.2, 0.5,
        0.7, 0.3, 0.2]),
 array([0.1, 0.9, 0.7, 0.2, 0.8, 0.8, 0.1, 0.8, 0.9, 0.2, 0.1, 0.1])]

In [42]:
bin_arr = convert_float_to_binary_mask(ts_pred[1])
bin_arr

array([0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0.])

In [43]:
convert_mask_to_cup_format(bin_arr)

[[1, 2], [4, 5], [7, 8]]

In [11]:
cup_f1_score(y_pred=ts_pred, y_true=ts_true)

[predictions, ground_truth] : 
[[[8, 9], [12, 13]], [[1, 2], [4, 5], [7, 8]]],
 ------------------------ 
[[[3, 5], [8, 9], [12, 13]], [[1, 2], [4, 5], [7, 8]]]


0.9

In [45]:
mat = np.array([[3, 3], [8, 9], [12, 13]])
mat

array([[ 3,  3],
       [ 8,  9],
       [12, 13]])

In [46]:
mat[~(mat[:, 0] == mat[:, 1])]

array([[ 8,  9],
       [12, 13]])